enum actionTypes {
  SET_AUTHORIZED = 'SET_AUTHORIZED',
  SET_LOADER = 'SET_LOADER',
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  SIGNOUT = 'SIGNOUT',
  CHECK_AUTHORIZATION_STATUS = 'CHECK_AUTHORIZATION_STATUS',
  SET_SIGNIN_ERROR_MSG = 'SET_SIGNIN_ERROR_MSG'
};

export default actionTypes;